package szwedo.bookhubapp.utils;

public enum EditProfileStatus {
    EMPTY_EMAIL,
    EMPTY_FIRST_NAME,
    EMPTY_LAST_NAME,
    EMPTY_ADDRESS,
    EMPTY_PHONE,
    EMPTY_PASSWORD,
    EMPTY_PASSWORD2,
    INCORRECT_EMAIL,
    INCORRECT_FIRST_NAME,
    INCORRECT_LAST_NAME,
    INCORRECT_ADDRESS,
    INCORRECT_PHONE,
    INCORRECT_PASSWORD,
    INCORRECT_PASSWORD2,
    CORRECT
}
